KEY_ROW_CYTO = 'CYTO'
KEY_ROW_FISH = 'FISH'
KEY_ROW_FLOW = 'FLOW'
KEY_ROW_MOLECULAR = 'MOLECULAR'
KEY_ROW_HISTOLOGY = 'HISTOLOGY'
KEY_ROW_TOTAL = 'TOTAL'

KEY_ROWS = [
    KEY_ROW_CYTO,
    KEY_ROW_FISH,
    KEY_ROW_FLOW,
    KEY_ROW_MOLECULAR,
    KEY_ROW_HISTOLOGY,
    KEY_ROW_TOTAL
]

KEY_COLUMN_REPORT = 'REPORT'
KEY_COLUMN_RECEIVED = 'RECEIVED'
KEY_COLUMN_TESTED = 'TESTED'
KEY_COLUMN_REPEATED = 'REPEATED'
KEY_COLUMN_ALL = 'ALL'

KEY_COLUMNS = [
    KEY_COLUMN_REPORT,
    KEY_COLUMN_RECEIVED,
    KEY_COLUMN_TESTED,
    KEY_COLUMN_REPEATED,
    KEY_COLUMN_ALL,
]

DEFAULT_HEADERS = {
    KEY_COLUMN_REPORT: 'REPORT',
    KEY_COLUMN_RECEIVED: 'RCV',
    KEY_COLUMN_TESTED: 'TST',
    KEY_COLUMN_REPEATED: 'RPT',
    KEY_COLUMN_ALL: 'ALL',
}

DEFAULT_TABLE = {
    KEY_COLUMN_REPORT: {
        KEY_ROW_CYTO: 'Cyto',
        KEY_ROW_FISH: 'FISH',
        KEY_ROW_FLOW: 'Flow',
        KEY_ROW_MOLECULAR: 'Mol',
        KEY_ROW_HISTOLOGY: 'Hist',
        KEY_ROW_TOTAL: 'TOTAL',
    },
    KEY_COLUMN_RECEIVED:{
        KEY_ROW_CYTO: 208,
        KEY_ROW_FISH: 360,
        KEY_ROW_FLOW: 357,
        KEY_ROW_MOLECULAR: 487,
        KEY_ROW_HISTOLOGY: 729,
        KEY_ROW_TOTAL: 2141,
    },
    KEY_COLUMN_TESTED: {
        KEY_ROW_CYTO: 543,
        KEY_ROW_FISH: 462,
        KEY_ROW_FLOW: 395,
        KEY_ROW_MOLECULAR: 346,
        KEY_ROW_HISTOLOGY: 833,
        KEY_ROW_TOTAL: 2579,
    },
    KEY_COLUMN_REPEATED: {
        KEY_ROW_CYTO: 339,
        KEY_ROW_FISH: 154,
        KEY_ROW_FLOW: 207,
        KEY_ROW_MOLECULAR: 204,
        KEY_ROW_HISTOLOGY: 333,
        KEY_ROW_TOTAL: 1237,
    },
    KEY_COLUMN_ALL: {
        KEY_ROW_CYTO: 1090,
        KEY_ROW_FISH: 976,
        KEY_ROW_FLOW: 959,
        KEY_ROW_MOLECULAR: 1037,
        KEY_ROW_HISTOLOGY: 1895,
        KEY_ROW_TOTAL: 5957,
    },
}
