# Generated by Django 3.2.9 on 2021-11-22 03:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('midIntl', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('cistzip', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('birthdate', models.CharField(max_length=30)),
            ],
        ),
    ]
