# Generated by Django 3.2.9 on 2021-11-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputModel',
            new_name='AccessionModel',
        ),
    ]
