# Generated by Django 3.2.9 on 2021-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_rename_accessionmodel_patientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='age',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='ssn',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
