# Generated by Django 3.2.9 on 2021-11-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20211122_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city_state_zip', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderingProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TreatingProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('specimenId', models.CharField(max_length=30)),
                ('cistzip', models.CharField(max_length=30)),
                ('specimentype', models.CharField(max_length=30)),
                ('date_collected', models.CharField(max_length=30)),
                ('icd10', models.CharField(max_length=30)),
                ('cell', models.CharField(max_length=30)),
                ('test', models.CharField(max_length=30)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.casemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=400)),
                ('interpretation', models.CharField(max_length=400)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.casemodel')),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_app.specimenmodel')),
            ],
        ),
        migrations.AddField(
            model_name='casemodel',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.facilitymodel'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='ordering_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.orderingprovidermodel'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.patientmodel'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='treating_provider',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.treatingprovidermodel'),
        ),
    ]
