# Generated by Django 3.2.9 on 2021-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20211122_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemodel',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='casemodel',
            name='ordering_provider',
        ),
        migrations.RemoveField(
            model_name='casemodel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='casemodel',
            name='treating_provider',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='case',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='specimen',
        ),
        migrations.RemoveField(
            model_name='specimenmodel',
            name='case',
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='patientId',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CaseModel',
        ),
        migrations.DeleteModel(
            name='FacilityModel',
        ),
        migrations.DeleteModel(
            name='OrderingProviderModel',
        ),
        migrations.DeleteModel(
            name='ReportModel',
        ),
        migrations.DeleteModel(
            name='SpecimenModel',
        ),
        migrations.DeleteModel(
            name='TreatingProviderModel',
        ),
    ]
