# Generated by Django 3.2.9 on 2021-11-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_casemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseModel',
        ),
    ]
