# Generated by Django 3.2.9 on 2021-11-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_casemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingProviderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='casemodel',
            name='ordering_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.orderingprovidermodel'),
            preserve_default=False,
        ),
    ]
