# Generated by Django 3.2.9 on 2021-11-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_auto_20211123_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemodel',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_app.patientmodel'),
            preserve_default=False,
        ),
    ]
