# Generated by Django 3.2.9 on 2021-11-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_casemodel_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseModel',
        ),
        migrations.DeleteModel(
            name='OrderingProviderModel',
        ),
    ]
