# Generated by Django 3.2.9 on 2021-11-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_reportselectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='address',
            new_name='pataddress',
        ),
        migrations.RenameField(
            model_name='patientmodel',
            old_name='cistzip',
            new_name='patcistzip',
        ),
        migrations.RenameField(
            model_name='patientmodel',
            old_name='phone',
            new_name='patphone',
        ),
    ]
