# Generated by Django 3.2.9 on 2021-11-27 08:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_auto_20211126_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderingprovidermodel',
            old_name='firstName',
            new_name='Ordering_physician',
        ),
        migrations.RenameField(
            model_name='treatingprovidermodel',
            old_name='firstName',
            new_name='Treating_physician',
        ),
        migrations.RemoveField(
            model_name='orderingprovidermodel',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='treatingprovidermodel',
            name='lastName',
        ),
        migrations.AddField(
            model_name='facilitymodel',
            name='facility_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
